export const APP_LOGIN = 'APP_LOGIN';

export const APP_INCOME_ADD = 'APP_INCOME_ADD';
export const APP_INCOME_EDIT = 'APP_INCOME_EDIT';
export const APP_INCOME_DELETE = 'APP_INCOME_DELETE';
export const APP_INCOME_TOTAL = 'APP_INCOME_TOTAL'

export const APP_SPEND_ADD = 'APP_SPEND_ADD';
export const APP_SPEND_EDIT = 'APP_SPEND_EDIT';
export const APP_SPEND_DELETE = 'APP_SPEND_DELETE';
export const APP_SPEND_TOTAL = 'APP_SPEND_TOTAL';

export const KEY_INCOME = '11111111113';
export const KEY_SPEND = '2222222222';


export const KEY_BANK_ACCOUNT = '33333333333';
